apiVersion: v1
kind: Secret
metadata:
  name: sda-training-secrets
  namespace: sda-training
type: Opaque
data:
  JWT_SECRET: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9zZGFfdHJhaW5pbmc=
  POSTGRES_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZTo1NDMyL3NkYV90cmFpbmluZw==
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  MONGO_ROOT_PASSWORD: Y2hhbmdlLW1lLW1vbmdvLXJvb3Q=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
